version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: expense_tracker
    restart: unless-stopped
    environment:
      POSTGRES_DB: expense
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: expense
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
