version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: socialmedia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: socialmedia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manish
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data:
